theme = "mytheme"

[editor]
line-number = "relative"
cursorline = true
true-color = true
rulers = [80, 120]

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
tabpad = "→"
newline = "⏎"

[editor.indent-guides]
render = true
skip-levels = 1
# character = "╎"
# character = "┆"
character = "┊"
# character = "⸽"

[keys.normal]
A-i = "move_line_up"
A-k = "move_line_down"
A-j = "move_char_left"
A-l = "move_char_right"
# C-s = ":w"
# C-p = ":open ~/AppData/Roaming/helix/config.toml"

[keys.insert]
A-i = "move_line_up"
A-k = "move_line_down"
A-j = "move_char_left"
A-l = "move_char_right"
# C-s = ":w"
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
