theme = "onedark"

[editor]
cursorline = true
rulers = [ 80, 120 ]

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
skip-levels = 1
# character = "╎"
# character = "┆"
character = "┊"
# character = "⸽"

[keys.normal]
C-s = ":w"

[keys.insert]
C-s = ":w"
